# ************ CCC - passing optimization flags ************ 
ifeq ($(CCC_OPTS),)
 CCC_OPTS =
endif

# Declarations
ifeq ($(ZCC),) 
 ZCC = llvm-gcc 
endif
ifeq ($(CC_OPTS),)
 CC_OPTS = -emit-llvm
endif
ifeq ($(LDCC),)
 LDCC = llvm-link
endif
ifeq ($(LD_OPTS),)
 LD_OPTS = -f -o a.out
endif

# Actions
all:		
	$(ZCC) $(CCC_OPTS) $(CC_OPTS) -c *.c
	$(LDCC) $(LD_OPTS) *.o

clean:
	rm -f a.out *.o *.a *.s *.i *.I
