# ************ CCC - passing optimization flags ************ 
ifeq ($(CCC_OPTS),)
 CCC_OPTS =
endif

# Declarations
ifeq ($(ZCC),) 
 ZCC = icc 
endif
ifeq ($(LDCC),)
 LDCC = icc
endif
ifeq ($(LD_OPTS),)
 LD_OPTS = -o a.out
endif

# Actions
all:		
	$(ZCC) $(CCC_OPTS) -c *.c
	$(LDCC) $(LD_OPTS) -lm -m32 *.o

clean:
	rm -f a.out *.o *.a *.s *.i *.I
